#
# This pod imports nfs-server.default.kube.local:/ into /usr/share/nginx/html
#

apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
    - name: m-web
      image: georgeluo/mongodb
      ports:
        - name: m-web
          containerPort: 27017
      volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/data/db"
  volumes:
    - name: nfs
      nfs:
        # FIXME: use the right hostname
        server: nfs-server
        path: "/"